/* error handling in js */
function foo(){
    //try catch block
    
}